"""empty message

Revision ID: 734480c215b0
Revises: 
Create Date: 2020-04-21 01:13:54.821527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734480c215b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'WIN', 'LOST', name='gamestatus'), nullable=False),
    sa.Column('datetime', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'FLAG', 'DISCOVERED', 'QUESTION', name='cellstatus'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('has_mine', sa.Boolean(), nullable=False),
    sa.Column('x', sa.BigInteger(), nullable=False),
    sa.Column('y', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cells')
    op.drop_table('games')
    # ### end Alembic commands ###
